Document: dyneinsle
Title: Debian dyneinsle Manual
Author: <insert document author here>
Abstract: This manual describes what dyneinsle is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dyneinsle/dyneinsle.sgml.gz

Format: postscript
Files: /usr/share/doc/dyneinsle/dyneinsle.ps.gz

Format: text
Files: /usr/share/doc/dyneinsle/dyneinsle.text.gz

Format: HTML
Index: /usr/share/doc/dyneinsle/html/index.html
Files: /usr/share/doc/dyneinsle/html/*.html
